name: Semgrep ISO Scan

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip3 install semgrep

      - name: Run Semgrep ISO Scan
        run: |
          semgrep --config ./iso-security.yaml --sarif --output semgrep-results.sarif ./src
