# name: Semgrep Security Scan

# on:
#   push:
#     branches: [main, develop]
#   pull_request:
#     branches: [main]

# jobs:
#   semgrep:
#     name: Semgrep Scan
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       # Install Semgrep
#       - name: Install Semgrep
#         run: |
#           pip install semgrep

#       # Run Semgrep (connect to Dashboard)
#       - name: Run Semgrep
#         run: |
#           semgrep \
#             --config=auto \
#             --sarif \
#             --output=semgrep.sarif \
#             src/
#         env:
#           SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

#       # Upload SARIF to GitHub Code Scanning
#       - name: Upload SARIF file
#         uses: github/codeql-action/upload-sarif@v3
#         with:
#           sarif_file: semgrep.sarif
#         if: always()
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
      - develop
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: 32 4 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
