# name: Semgrep Security Scan

# on:
#   push:
#     branches: [main, develop]
#   pull_request:
#     branches: [main]

# jobs:
#   semgrep:
#     name: Semgrep Scan
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       # Install Semgrep
#       - name: Install Semgrep
#         run: |
#           pip install semgrep

#       # Run Semgrep (connect to Dashboard)
#       - name: Run Semgrep
#         run: |
#           semgrep \
#             --config=auto \
#             --sarif \
#             --output=semgrep.sarif \
#             src/
#         env:
#           SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

#       # Upload SARIF to GitHub Code Scanning
#       - name: Upload SARIF file
#         uses: github/codeql-action/upload-sarif@v3
#         with:
#           sarif_file: semgrep.sarif
#         if: always()
name: Semgrep Scan

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: true
          uploadSarif: true
          branch: ${{ github.ref_name }} # ส่ง branch name จริง
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif
