# name: Semgrep Security Scan

# on:
#   push:
#     branches: [main, develop]
#   pull_request:
#     branches: [main]

# jobs:
#   semgrep:
#     name: Semgrep Scan
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       # Install Semgrep
#       - name: Install Semgrep
#         run: |
#           pip install semgrep

#       # Run Semgrep (connect to Dashboard)
#       - name: Run Semgrep
#         run: |
#           semgrep \
#             --config=auto \
#             --sarif \
#             --output=semgrep.sarif \
#             src/
#         env:
#           SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

#       # Upload SARIF to GitHub Code Scanning
#       - name: Upload SARIF file
#         uses: github/codeql-action/upload-sarif@v3
#         with:
#           sarif_file: semgrep.sarif
#         if: always()
name: Semgrep Scan

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          publish: true # ส่งผลขึ้น Semgrep Dashboard
          branch: ${{ github.ref_name }} # branch ที่ต้องการ show ใน dashboard
        env:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
